name: Deploy Node.js App (Primary + Secondary)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - run: npm install

  deploy-primary:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Primary
        uses: azure/webapps-deploy@v3
        with:
          app-name: project4-primarywebapp
          publish-profile: ${{ secrets.AZURE_PRIMARY_PUBLISH_PROFILE }}
          package: .

  deploy-secondary:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Secondary
        uses: azure/webapps-deploy@v3
        with:
          app-name: project4-secondarywebapp
          publish-profile: ${{ secrets.AZURE_SECONDARY_PUBLISH_PROFILE }}
          package: .
