name: Build and deploy Node.js app to Azure Web App - project4-primarywebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build (if any)
        run: npm run build --if-present

      - name: Run tests (if any)
        run: npm run test --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_84684D91E3054558A0B2D93C43417F19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D73CFAF91725444082A5AFD18167E39C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93A96B1826494E72A651AD5A54E874AE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'project4-primarywebapp'
          slot-name: 'Production'
          package: .
